---
title: "Weitere Beispiele"
author: "Jan-Philipp Kolb"
date: "7 September 2018"
output: beamer_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```



## PLZ Datensatz einlesen

- [**Quelle**](http://arnulf.us/PLZ) für PLZ Shapefiles

```{r,eval=athome,echo=F}
data_path <- "D:/GESIS/data/"
```

```{r,eval=GESIS,echo=F}
data_path <- "D:/Daten/Daten/GeoDaten/"
```


```{r}
library(rgdal)
```


```{r}
setwd(data_path)
plz <- readOGR ("post_pl.shp","post_pl")
```

## Die Daten plotten

```{r}
plzbereich <- substr(plz@data$PLZ99,1,2)
plot(plz[plzbereich=="68",])
```


## [Räumliche Stichprobe](https://www.rdocumentation.org/packages/sp/versions/1.3-1/topics/spsample)

```{r}
set.seed(323)
n <- 100
sampplz <- "68239"
spatsamp <- spsample(plz[plz@data$PLZ99==sampplz,], 
                     n,type="random")
```

## Reverse Geokodierung

```{r,eval=F}
spatlist <- list()
for (i in 1:n){
  spatlist[[i]] <- ggmap::revgeocode(c(spatsamp[i,]$x,
                                       spatsamp[i,]$y))  
}

spatvec <- unlist(spatlist)
spatsamp$adress <- spatvec
```

```{r,eval=F,echo=F}
save(spatsamp,file=paste0("../data/spatsamp_",sampplz,".RData"))
```

```{r,echo=F}
load(paste0("../data/spatsamp_",sampplz,".RData"))
```
