---
title: "Karte Gemeinden"
author: "Jan-Philipp Kolb"
date: "29 August 2018"
output: beamer_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
GESIS <- T
athome <- !GESIS
```

## [Shapefile mit Regionalschlüssel](http://www.geodatenzentrum.de/geodaten/gdz_rahmen.gdz_div?gdz_spr=deu&gdz_akt_zeile=5&gdz_anz_zeile=1&gdz_unt_zeile=13&gdz_user_id=0) herunterladen

```{r,eval=GESIS,echo=F}
vg250path <- "J:/Work/GESISPanel_DATA/01_post_processing/c01/e_2017/ee/01_wave/data/com/geodata/vg250/"
```

```{r,eval=athome,echo=F}
vg250path <- "D:/GESIS/data/vg250_3112.utm32s.shape.ebenen/vg250_ebenen"
```


```{r}
library(rgdal)
```


```{r}
setwd(vg250path)
VG250 <- readOGR ("VG250_GEM.shp","VG250_GEM")
```

```{r,eval=athome}
bla <- substr(VG250@data$AGS_0,1,2)
plot(VG250[bla=="11",])
```


## [Räumliche Stichprobe](https://www.rdocumentation.org/packages/sp/versions/1.3-1/topics/spsample)

```{r}
spatsamp <- spsample(VG250[bla=="11",], 100,type="random")
```

```{r}
# EPSG: 3857
newData<-spTransform(spatsamp, CRS("+init=epsg:3857"))
#sp::proj4string(poi) <- sp::CRS("+init=epsg:4326")
# res <- spTransform(poi, CRS("+init=epsg:3035"))
                      
```





```{r,eval=F,echo=F}
VG250 <- readOGR ("VG250_F.shp","VG250_F")
head(VG250@data)
```

- [Informationen zum AGS](https://de.wikipedia.org/wiki/Amtlicher_Gemeindeschl%C3%BCssel)

```{r}
rs <- as.character(VG250@data$RS)
nchar_rs <- nchar(rs)

agsmap <- VG250[nchar_rs==12,]
agsmap$ags <- paste0(substr(as.character(agsmap@data$RS),1,5),substr(as.character(agsmap@data$RS),10,12))
```

```{r}
bla <- substr(agsmap$ags,1,2)

plot(agsmap[bla=="11",])
```

## Links

- [Früherer Kurs zum Thema](https://github.com/Japhilko/GeoData/blob/master/2017/slides/polygonSources.md)