---
title: "Simple Features"
author: "Jan-Philipp Kolb"
date: "23 Oktober 2018"
output:
  beamer_presentation:
    colortheme: beaver
    fonttheme: structurebold
    highlight: tango
    fig_caption: no
    keep_tex: yes
    theme: CambridgeUS
  slidy_presentation: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,fig.height=4)
athome <- T
```

## Das Paket `sf`

> Simple Features for R 

```{r}
library(sf)
```


```{r,eval=F}
demo(sf::affine)
```



## Beispieldaten bekommen

<!--
https://cran.r-project.org/web/packages/sf/vignettes/sf1.html
-->

```{r}
library(osmdata)
bb_poly <- getbb(place_name = "Amsterdam", 
                 format_out = "polygon")

```


```{r}
ls <- st_multilinestring(bb_poly)
```


```{r}
pol <- sf::st_polygon(bb_poly)
class(pol)
```

```{r,echo=F,eval=F}
ab <- st_polygonize(ls)
ab <- st_geometrycollection(list(pol))
str(ab)
```


```{r}
bb_poly_ma <- getbb(place_name = "Mannheim", 
                 format_out = "polygon")

plot(bb_poly_ma)
```



```{r,eval=F}
bb_poly_hd <- getbb(place_name = "Heidelberg", 
                 format_out = "polygon")
```


```{r,eval=F,echo=F}
ls <- st_multilinestring(bb_poly_ma)
ab <- st_polygonize(ls)
```


<!--
Problem ist, dass man nichts sieht, wenn man das plottet

# folgendes funktioniert nicht
-->

```{r,eval=F,echo=F}
mpol <- sf::st_multipolygon(bb_poly)
```


```{r}
# x <- osmdata_sf(pol)
```

## [Graphiken mit `sf`](https://r-spatial.github.io/sf/articles/sf5.html)

```{r}
demo(nc, ask = FALSE, echo = FALSE)
plot(nc)
```


## [Shapefiles mit `sf` importieren](https://cran.r-project.org/web/packages/sf/vignettes/sf2.html)


```{r,eval=athome,echo=F}
data_path <- "D:/GESIS/data/"
```

```{r}
setwd(data_path)
plz <- st_read("post_pl.shp")
```

<!--
https://www.r-spatial.org/r/2018/01/08/sf-0.6-0.html
-->